function out = readQdJsonFile(path)

fid = fopen(path);

out = struct('TX', cell(1,1), ...
    'RX', cell(1,1), ...
    'PAA_TX', cell(1,1), ...
    'PAA_RX', cell(1,1), ...
    'Delay', cell(1,1), ...
    'Gain', cell(1,1), ...
    'Phase', cell(1,1), ...
    'AODEL', cell(1,1), ...
    'AODAZ', cell(1,1), ...
    'AOAEL', cell(1,1), ...
    'AOAAZ', cell(1,1) ...
    );

line = 1;
isEof = false;
while ~isEof
    tline = fgetl(fid);
    if ischar( tline )
        out(line) = jsondecode(tline);
        line = line + 1;
    else
        isEof = true;
    end
end
fclose(fid);

end