function frmRotMpInfoOut = reverseFrmRotMpInfo(frmRotMpInfo)
L = length(frmRotMpInfo);

if isempty(frmRotMpInfo)
    frmRotMpInfoOut = frmRotMpInfo;
else
%     frmRotMpInfoOut = struct('dod' ,mat2cell(reshape([frmRotMpInfo.doa], 3, []).', ones(1,L)).', ...
%         'doa' ,mat2cell(reshape([frmRotMpInfo.dod], 3, []).', ones(1,L)).', ...
%         'TxVel' ,mat2cell(reshape([frmRotMpInfo.RxVel], 3, []).', ones(1,L)).', ...
%         'RxVel' ,mat2cell(reshape([frmRotMpInfo.TxVel], 3, []).', ones(1,L)).' ...
%         );
    frmRotMpInfoOut = struct('dod', cell(1,L), ...
        'doa',  cell(1,L), ...
        'TxVel', cell(1,L), ...
        'RxVel', cell(1,L) ...
        );
    [frmRotMpInfoOut.dod] = deal(frmRotMpInfo.doa);
    [frmRotMpInfoOut.doa] = deal(frmRotMpInfo.dod);
    [frmRotMpInfoOut.TxVel] = deal(frmRotMpInfo.RxVel);
    [frmRotMpInfoOut.RxVel] = deal(frmRotMpInfo.TxVel);


end
end